# theme = "onelight"
# theme = "tokyonight_storm"
theme = "zed_onedark"

[keys.normal]
F1 = ":set whitespace.render none"
F2 = ":set whitespace.render all"
X = ["extend_line_up", "extend_to_line_bounds"]
G = ":sh git status"
L = ":sh pwd & echo ---- & ls"
# "A-s" = "signature_help"

# [keys.insert]
# "A-s" = "signature_help"

[editor.smart-tab]
enable = false

[editor]
auto-pairs = false
auto-format = false

# [editor.lsp]
# auto-signature-help = false
