# theme = "catppuccin_frappe"
# theme = "everforest_dark"
# theme = "kaolin-dark"
# theme = "bogster"
# theme = "material_oceanic"
# theme = "material_darker"
# theme = "ayu_dark"
# theme = "dark_high_contrast"
# theme = "dracula_at_night"
# theme = "carbonfox"
theme = "bogster_light"

[keys.normal]
F1 = ":set whitespace.render none"
F2 = ":set whitespace.render all"
X = ["extend_line_up", "extend_to_line_bounds"]
G = ":sh git status"
L = ":sh pwd & echo ---- & ls"

[editor.smart-tab]
enable = false

[editor]
auto-pairs = false
