theme = "everforest_dark"

[keys.normal]
F1 = ":set whitespace.render none"
F2 = ":set whitespace.render all"
X = ["extend_line_up", "extend_to_line_bounds"]
G = ":sh git status"
L = ":sh pwd & echo ---- & ls"

[editor.smart-tab]
enable = false

[editor]
auto-pairs = false
