[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["--quiet", "-"] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"
