[window]
# decorations = "Full"
decorations = "None"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
italic = { family = "JetBrainsMono Nerd Font", style = "Medium Italic" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12

[selection]
save_to_clipboard = true

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
